version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: dependencies-node8-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum "elm-package.json" }}-{{ checksum "tests/elm-package.json" }}

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-node8-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum "elm-package.json" }}-{{ checksum "tests/elm-package.json" }}

      - run:
          name: Tests
          command: npm test
